language: ruby
rvm:
- 2.2
env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_VERSION=6.12
sudo: required
git:
  quiet: true
branches:
  only:
    - master

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - gem install asciidoctor -v 1.5.7.1
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/wkhtmlto* /usr/bin
  - sudo apt-get install -y pdftk

script:
  - ./build-pathway

after_success:
  - ./travis-push.sh
